### ISSUE TITLE
delete and delete_collection on CrateDBVectorSearch don't delete the actual embeddings

### ISSUE THREAD

**Issue by andnig** [crate-workbench/langchain#11]
### System Info

Langchain 0.0.315

### Who can help?

@amotl 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [x] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python

from langchain.schema import Document

doc = Document(page_content="this is such a nice text")
vector_store = CrateDBVectorSearch.from_documents([doc], OpenAIEmbeddings(), collection_name="wow_such_nice", connection_string="crate://localhost:4200?schema=langchain")
vector_store.delete_collection()

```

### Expected behavior

The collection should be deleted as well as all embeddings which are part of this collection.
While the collection gets deleted from the collection table, the embeddings of this collection in the `embedding` table are still there.

**Comment by amotl** [comment]
Hi @andnig,

thanks for your report. @ckurze recently reported GH-5, and I think we made a few improvements.

You are reporting that you observed the problem with LangChain 0.0.315. The current `cratedb` branch is on LangChain version 0.0.338. Can I ask you to try again, using the most recent version here?

With kind regards,
Andreas.

**Comment by hlcianfagna** [comment]
Relates with https://github.com/crate/crate/issues/1376

**Comment by ckurze** [comment]
Thanks for reporting - as soon as we slightly change the logic how we handle tables and embeddings (https://github.com/crate-workbench/langchain/issues/12), this operation will translate into a `DELETE FROM <collection_name>` or `DROP TABLE <collection_name>`, respectively. We should prioritize https://github.com/crate-workbench/langchain/issues/12 over this issue.

**Comment by amotl** [comment]
Dear @andnig,

GH-14 fixed this problem. Thanks again for the report.

With kind regards,
Andreas.
