### ISSUE TITLE
Cannot create embeddings with latest cratedb branch: Wrong embedding dimensions

### ISSUE THREAD

**Issue by andnig** [crate-workbench/langchain#22]
### System Info

langchain 0.0.339rc1 (this repos `cratedb` branch)

### Who can help?

@amo

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Install the latest crate langchain and openai packages, using
    ```bash
    pip install 'langchain[cratedb] @ git+https://github.com/crate-workbench/langchain.git@cratedb#subdirectory=libs/langchain' --upgrade
    pip install openai --upgrade
    ```
2. run this script
    ```python 
    from langchain.schema import Document
    from langchain.vectorstores.cratedb import CrateDBVectorSearch
    from langchain.embeddings.openai import OpenAIEmbeddings
    
    doc = Document(page_content="this is such a nice text")
    vector_store = CrateDBVectorSearch.from_documents([doc], OpenAIEmbeddings(api_key="<sk-your-api-key>"), collection_name="wow_such_nice", connection_string="crate://localhost:4200?schema=langchain5")
    ```

**Result:** 
ProgrammingError: SQLParseException[The number of vector dimensions does not match the field type]

The tables embedding and collection are created, however with the wrong embedding dimensions. The default 1024 are used instead of the 1536

With the `testing` branch, everything works as expected.

### Expected behavior

With the latest `cratedb` branch (and as a matter of fact also for this new storage strategy branch), it's not possible to create embedding entries when using the CrateDBVectorSearch interface.
The tables `embedding` and `collection` are created however with only 1024 dimensions, and the from_documents call fails (naturally)

Maybe the quite dramatic change of the openai package between 0.28 and 1.0 resulted in CrateDBs Langchain implementation not being able to find the correct embedding dimension anymore?

**Comment by amotl** [comment]
Hi Andreas,

thanks a stack for reporting this problem.

> Maybe the quite dramatic change of the openai package between 0.28 and 1.0 resulted in CrateDBs Langchain implementation not being able to find the correct embedding dimension anymore?

It is more likely that our recent improvements made things go south. We will look into it.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

GH-23 has a fix for this regression. It had nothing to do with OpenAI library updates, but most probably was introduced by GH-13 last week. Thanks again for reporting this flaw.

Witih kind regards,
Andreas.

**Comment by amotl** [comment]
The fix has been merged. Can we humbly ask you to try again, and report back if that resolves the problem?

**Comment by andnig** [comment]
Can confirm. Thanks!

**Comment by amotl** [comment]
Hi Andreas.

Thank you very much for your report. Indeed, something went wrong and the fixup commit from GH-23 was missing. I've just fixed the `cratedb` and `embedding-table-per-collection` branches to include it again.

With kind regards,
Andreas.
