### ISSUE TITLE
Vector Store: "Collection not found" when using `pre_delete_collection=True`

### ISSUE THREAD

**Issue by ckurze** [crate-workbench/langchain#5]
## Problem

When using `pre_delete_collection=True`, there is only an error stating "Collection not found", the actual collection is not deleted / emptied.

## Details
Example: `vector_search.ipynb`

```python
COLLECTION_NAME = "state_of_the_union_test"

embeddings = OpenAIEmbeddings()

db = CrateDBVectorSearch.from_documents(
    embedding=embeddings,
    documents=docs,
    collection_name=COLLECTION_NAME,
    connection_string=CONNECTION_STRING,
    pre_delete_collection=True, 
)
```

**Comment by amotl** [comment]
Hi Christian,

thanks for reporting. I've added a self-contained example program at [^1], but I haven't been able to reproduce any flaw. I tried it with a CrateDB instance already running, and I also tried once more with a recycled one, without any existing tables.

Can I ask you to try again? Maybe the situation was improved in the meanwhile, and the flaw was resolved by some other fix added recently?

With kind regards,
Andreas.


[^1]: https://gist.github.com/amotl/75f27244951f201b89db0d8394f97a0e

**Comment by amotl** [comment]
Indeed, I am also observing problems here.

```
____________________________________________________________ notebook: nbregression(vector_search) _____________________________________________________________
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
docs_with_score[0]
------------------

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[20], line 1
----> 1 docs_with_score[0]

IndexError: list index out of range
```

```
### Overwriting a vector store

If you have an existing collection, you can overwrite it by using `from_documents`,
and setting `pre_delete_collection = True`.
#%%
db = CrateDBVectorSearch.from_documents(
    documents=docs,
    embedding=embeddings,
    collection_name=COLLECTION_NAME,
    connection_string=CONNECTION_STRING,
    pre_delete_collection=True,
)
#%%
docs_with_score = db.similarity_search_with_score("foo")
#%%
docs_with_score[0]
#%% md
```

**Comment by amotl** [comment]
We may have been able to reproduce the flaw on behalf of bringing in corresponding software tests for the accompanying Jupyter Notebooks.

- https://github.com/crate/cratedb-examples/pull/97

```shell
pytest -k vector_search
```

![image](https://github.com/crate-workbench/langchain/assets/453543/8cf9517a-a45e-42c6-9251-cb10b7d81be5)

**Comment by amotl** [comment]
> When using `pre_delete_collection=True`, there is only an error stating "Collection not found".

Indeed, this is the only occurrance of `logger.warning` within `pgvector`. In this manner, it feels a bit like a stray log item, but C'est la vie.
```
$ ag "warning.*collection not found"

libs/langchain/langchain/vectorstores/pgembedding.py
219:                self.logger.warning("Collection not found")

libs/langchain/langchain/vectorstores/pgvector.py
189:                self.logger.warning("Collection not found")
```

> the actual collection is not deleted / emptied.

**Comment by amotl** [comment]
>> [...] the actual collection is not deleted / emptied.
>
> Will have to be investigated.

By using the standalone example program [cratedb-langchain-pre-delete-collection.py](https://gist.github.com/amotl/f8a62404e23a172f0671842e965dae48), you can exercise that the `Result count` output is different when disabling the `pre_delete_collection=True` line.

You may need to invoke the program a few times with and without the line to see the difference. I guess this demonstrates it works well?
